// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2021 moonheart08 <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared.Administration;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));

            InitializeAnnounceTypeOptions();
            InitializeStyleOptions();
            InitializePresets();

            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;
        }

        private void InitializeAnnounceTypeOptions()
        {
            AddLocalizedOption(AnnounceMethod, "admin-announce-type-station", AdminAnnounceType.Station);
            AddLocalizedOption(AnnounceMethod, "admin-announce-type-server", AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;

            OptionsTabs.SetTabTitle(0, _localization.GetString("admin-announce-presets-tab-title"));
            OptionsTabs.SetTabTitle(1, _localization.GetString("admin-announce-custom-tab-title"));
        }

        private void InitializeStyleOptions()
        {
            AddLocalizedOption(SoundOption, "admin-announce-sound-default", AdminAnnounceSound.Default);
            AddLocalizedOption(SoundOption, "admin-announce-sound-alert", AdminAnnounceSound.Alert);
            AddLocalizedOption(SoundOption, "admin-announce-sound-intercept", AdminAnnounceSound.Intercept);
            AddLocalizedOption(SoundOption, "admin-announce-sound-meteors", AdminAnnounceSound.Meteors);
            AddLocalizedOption(SoundOption, "admin-announce-sound-radiation", AdminAnnounceSound.Radiation);
            AddLocalizedOption(SoundOption, "admin-announce-sound-shuttle-called", AdminAnnounceSound.ShuttleCalled);
            AddLocalizedOption(SoundOption, "admin-announce-sound-power-on", AdminAnnounceSound.PowerOn);
            AddLocalizedOption(SoundOption, "admin-announce-sound-evil", AdminAnnounceSound.Evil);
            AddLocalizedOption(SoundOption, "admin-announce-sound-mercenary", AdminAnnounceSound.Mercenary);
            AddLocalizedOption(SoundOption, "admin-announce-sound-soviet", AdminAnnounceSound.Soviet);
            SoundOption.SelectId(0);
            SoundOption.OnItemSelected += OnOptionSelected;

            AddLocalizedOption(ColorOption, "admin-announce-color-gold", AdminAnnounceColor.Gold);
            AddLocalizedOption(ColorOption, "admin-announce-color-purple", AdminAnnounceColor.Purple);
            AddLocalizedOption(ColorOption, "admin-announce-color-orange", AdminAnnounceColor.Orange);
            AddLocalizedOption(ColorOption, "admin-announce-color-red", AdminAnnounceColor.Red);
            AddLocalizedOption(ColorOption, "admin-announce-color-cyan", AdminAnnounceColor.Cyan);
            AddLocalizedOption(ColorOption, "admin-announce-color-blue", AdminAnnounceColor.Blue);
            AddLocalizedOption(ColorOption, "admin-announce-color-green", AdminAnnounceColor.Green);
            ColorOption.SelectId(0);
            ColorOption.OnItemSelected += OnOptionSelected;

            AddLocalizedOption(FontOption, "admin-announce-font-default", AdminAnnounceFont.Default);
            AddLocalizedOption(FontOption, "admin-announce-font-monospace", AdminAnnounceFont.Monospace);
            AddLocalizedOption(FontOption, "admin-announce-font-box", AdminAnnounceFont.BoxRound);
            AddLocalizedOption(FontOption, "admin-announce-font-animal", AdminAnnounceFont.AnimalSilence);
            FontOption.SelectId(0);
            FontOption.OnItemSelected += OnOptionSelected;

            AddLocalizedOption(FontSizeOption, "admin-announce-font-size-small", 10);
            AddLocalizedOption(FontSizeOption, "admin-announce-font-size-medium", 12);
            AddLocalizedOption(FontSizeOption, "admin-announce-font-size-large", 14);
            AddLocalizedOption(FontSizeOption, "admin-announce-font-size-xl", 16);
            FontSizeOption.SelectId(1);
            FontSizeOption.OnItemSelected += OnOptionSelected;
        }

        private void InitializePresets()
        {
            PresetEvilButton.OnPressed += _ => SetPreset(
                _localization.GetString("admin-announce-preset-evil-announcer"),
                _localization.GetString("admin-announce-preset-evil-text"),
                AdminAnnounceSound.Evil,
                AdminAnnounceColor.Purple,
                AdminAnnounceFont.AnimalSilence,
                14,
                true);

            PresetMercenaryButton.OnPressed += _ => SetPreset(
                _localization.GetString("admin-announce-preset-mercenary-announcer"),
                _localization.GetString("admin-announce-preset-mercenary-text"),
                AdminAnnounceSound.Mercenary,
                AdminAnnounceColor.Orange,
                AdminAnnounceFont.Monospace,
                12,
                true);

            PresetSovietButton.OnPressed += _ => SetPreset(
                _localization.GetString("admin-announce-preset-soviet-announcer"),
                _localization.GetString("admin-announce-preset-soviet-text"),
                AdminAnnounceSound.Soviet,
                AdminAnnounceColor.Red,
                AdminAnnounceFont.BoxRound,
                14,
                true);
        }

        private void AddLocalizedOption<T>(OptionButton option, string locKey, T metadata)
            where T : notnull
        {
            var index = option.ItemCount;
            option.AddItem(_localization.GetString(locKey));
            option.SetItemMetadata(index, metadata);
        }

        private void SetPreset(
            string announcer,
            string text,
            AdminAnnounceSound sound,
            AdminAnnounceColor color,
            AdminAnnounceFont font,
            int fontSize,
            bool includeSuffix)
        {
            Announcer.Text = announcer;
            Announcement.TextRope = new Rope.Leaf(text);

            SelectOption(SoundOption, sound);
            SelectOption(ColorOption, color);
            SelectOption(FontOption, font);
            SelectOption(FontSizeOption, fontSize);
            IncludeAnnouncementSuffix.Pressed = includeSuffix;

            AnnounceButton.Disabled = false;
        }

        private static void SelectOption<T>(OptionButton option, T value)
            where T : struct
        {
            for (var i = 0; i < option.ItemCount; i++)
            {
                if (option.GetItemMetadata(i) is not T metadata || !EqualityComparer<T>.Default.Equals(metadata, value))
                    continue;

                option.SelectId(i);
                return;
            }
        }

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = string.IsNullOrWhiteSpace(Rope.Collapse(Announcement.TextRope));
        }

        private static void OnOptionSelected(OptionButton.ItemSelectedEventArgs args)
        {
            args.Button.SelectId(args.Id);
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station;
        }

        public AdminAnnounceType SelectedAnnounceType =>
            (AdminAnnounceType?) AnnounceMethod.SelectedMetadata ?? AdminAnnounceType.Station;

        public AdminAnnounceSound SelectedSound =>
            (AdminAnnounceSound?) SoundOption.SelectedMetadata ?? AdminAnnounceSound.Default;

        public AdminAnnounceColor SelectedColor =>
            (AdminAnnounceColor?) ColorOption.SelectedMetadata ?? AdminAnnounceColor.Gold;

        public AdminAnnounceFont SelectedFont =>
            (AdminAnnounceFont?) FontOption.SelectedMetadata ?? AdminAnnounceFont.Default;

        public int SelectedFontSize =>
            (int?) FontSizeOption.SelectedMetadata ?? 12;

        public bool ShouldIncludeAnnouncementSuffix => IncludeAnnouncementSuffix.Pressed;
    }
}
