// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2021 moonheart08 <moonheart08@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Rinkashikachi <15rinkashikachi15@gmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared.Administration;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            OptionsTabs.SetTabTitle(0, _localization.GetString("admin-announce-presets-tab-title"));
            OptionsTabs.SetTabTitle(1, _localization.GetString("admin-announce-custom-tab-title"));

            SoundOption.AddItem(_localization.GetString("admin-announce-sound-default"));
            SoundOption.SetItemMetadata(0, AdminAnnounceSound.Default);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-alert"));
            SoundOption.SetItemMetadata(1, AdminAnnounceSound.Alert);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-intercept"));
            SoundOption.SetItemMetadata(2, AdminAnnounceSound.Intercept);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-meteors"));
            SoundOption.SetItemMetadata(3, AdminAnnounceSound.Meteors);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-radiation"));
            SoundOption.SetItemMetadata(4, AdminAnnounceSound.Radiation);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-shuttle-called"));
            SoundOption.SetItemMetadata(5, AdminAnnounceSound.ShuttleCalled);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-power-on"));
            SoundOption.SetItemMetadata(6, AdminAnnounceSound.PowerOn);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-evil"));
            SoundOption.SetItemMetadata(7, AdminAnnounceSound.Evil);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-mercenary"));
            SoundOption.SetItemMetadata(8, AdminAnnounceSound.Mercenary);
            SoundOption.AddItem(_localization.GetString("admin-announce-sound-soviet"));
            SoundOption.SetItemMetadata(9, AdminAnnounceSound.Soviet);
            SoundOption.SelectId(0);
            SoundOption.OnItemSelected += SoundOptionOnOnItemSelected;

            ColorOption.AddItem(_localization.GetString("admin-announce-color-gold"));
            ColorOption.SetItemMetadata(0, AdminAnnounceColor.Gold);
            ColorOption.AddItem(_localization.GetString("admin-announce-color-purple"));
            ColorOption.SetItemMetadata(1, AdminAnnounceColor.Purple);
            ColorOption.AddItem(_localization.GetString("admin-announce-color-orange"));
            ColorOption.SetItemMetadata(2, AdminAnnounceColor.Orange);
            ColorOption.AddItem(_localization.GetString("admin-announce-color-red"));
            ColorOption.SetItemMetadata(3, AdminAnnounceColor.Red);
            ColorOption.AddItem(_localization.GetString("admin-announce-color-cyan"));
            ColorOption.SetItemMetadata(4, AdminAnnounceColor.Cyan);
            ColorOption.AddItem(_localization.GetString("admin-announce-color-blue"));
            ColorOption.SetItemMetadata(5, AdminAnnounceColor.Blue);
            ColorOption.AddItem(_localization.GetString("admin-announce-color-green"));
            ColorOption.SetItemMetadata(6, AdminAnnounceColor.Green);
            ColorOption.SelectId(0);
            ColorOption.OnItemSelected += ColorOptionOnOnItemSelected;

            FontOption.AddItem(_localization.GetString("admin-announce-font-default"));
            FontOption.SetItemMetadata(0, AdminAnnounceFont.Default);
            FontOption.AddItem(_localization.GetString("admin-announce-font-monospace"));
            FontOption.SetItemMetadata(1, AdminAnnounceFont.Monospace);
            FontOption.AddItem(_localization.GetString("admin-announce-font-box"));
            FontOption.SetItemMetadata(2, AdminAnnounceFont.BoxRound);
            FontOption.AddItem(_localization.GetString("admin-announce-font-animal"));
            FontOption.SetItemMetadata(3, AdminAnnounceFont.AnimalSilence);
            FontOption.SelectId(0);
            FontOption.OnItemSelected += FontOptionOnOnItemSelected;

            FontSizeOption.AddItem(_localization.GetString("admin-announce-font-size-small"));
            FontSizeOption.SetItemMetadata(0, 10);
            FontSizeOption.AddItem(_localization.GetString("admin-announce-font-size-medium"));
            FontSizeOption.SetItemMetadata(1, 12);
            FontSizeOption.AddItem(_localization.GetString("admin-announce-font-size-large"));
            FontSizeOption.SetItemMetadata(2, 14);
            FontSizeOption.AddItem(_localization.GetString("admin-announce-font-size-xl"));
            FontSizeOption.SetItemMetadata(3, 16);
            FontSizeOption.SelectId(1);
            FontSizeOption.OnItemSelected += FontSizeOptionOnOnItemSelected;

            PresetEvilButton.OnPressed += _ => SetPreset(
                _localization.GetString("admin-announce-preset-evil-announcer"),
                _localization.GetString("admin-announce-preset-evil-text"),
                AdminAnnounceSound.Evil,
                AdminAnnounceColor.Purple,
                AdminAnnounceFont.AnimalSilence,
                14,
                true);
            PresetMercenaryButton.OnPressed += _ => SetPreset(
                _localization.GetString("admin-announce-preset-mercenary-announcer"),
                _localization.GetString("admin-announce-preset-mercenary-text"),
                AdminAnnounceSound.Mercenary,
                AdminAnnounceColor.Orange,
                AdminAnnounceFont.Monospace,
                12,
                true);
            PresetSovietButton.OnPressed += _ => SetPreset(
                _localization.GetString("admin-announce-preset-soviet-announcer"),
                _localization.GetString("admin-announce-preset-soviet-text"),
                AdminAnnounceSound.Soviet,
                AdminAnnounceColor.Red,
                AdminAnnounceFont.BoxRound,
                14,
                true);

            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;
        }

        private void SetPreset(
            string announcer,
            string text,
            AdminAnnounceSound sound,
            AdminAnnounceColor color,
            AdminAnnounceFont font,
            int fontSize,
            bool includeSuffix)
        {
            Announcer.Text = announcer;
            Announcement.TextRope = new Rope.Leaf(text);

            SelectOption(SoundOption, sound);
            SelectOption(ColorOption, color);
            SelectOption(FontOption, font);
            SelectOption(FontSizeOption, fontSize);
            IncludeAnnouncementSuffix.Pressed = includeSuffix;

            AnnounceButton.Disabled = false;
        }

        private static void SelectOption<T>(OptionButton option, T value)
            where T : struct
        {
            for (var i = 0; i < option.ItemCount; i++)
            {
                if (option.GetItemMetadata(i) is not T metadata || !EqualityComparer<T>.Default.Equals(metadata, value))
                    continue;

                option.SelectId(i);
                return;
            }
        }

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void SoundOptionOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            SoundOption.SelectId(args.Id);
        }

        private void ColorOptionOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            ColorOption.SelectId(args.Id);
        }

        private void FontOptionOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            FontOption.SelectId(args.Id);
        }

        private void FontSizeOptionOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            FontSizeOption.SelectId(args.Id);
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station;
        }

        public AdminAnnounceSound SelectedSound =>
            (AdminAnnounceSound?) SoundOption.SelectedMetadata ?? AdminAnnounceSound.Default;

        public AdminAnnounceColor SelectedColor =>
            (AdminAnnounceColor?) ColorOption.SelectedMetadata ?? AdminAnnounceColor.Gold;

        public AdminAnnounceFont SelectedFont =>
            (AdminAnnounceFont?) FontOption.SelectedMetadata ?? AdminAnnounceFont.Default;

        public int SelectedFontSize =>
            (int?) FontSizeOption.SelectedMetadata ?? 12;

        public bool ShouldIncludeAnnouncementSuffix => IncludeAnnouncementSuffix.Pressed;
    }
}
