// SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Skubman <ba.fallaria@gmail.com>
// SPDX-FileCopyrightText: 2024 Tadeo <td12233a@gmail.com>
// SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(LogProbeUiState state)
    {
        ProbedDeviceContainer.RemoveAllChildren();

        // Reverse so oldest entries appear at the bottom.
        state.PulledLogs.Reverse();

        var count = 1;
        foreach (var log in state.PulledLogs)
        {
            var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
            var accessorLabelText = log.Accessor;
            var entry = new LogProbeUiEntry(count, timeLabelText, accessorLabelText);

            ProbedDeviceContainer.AddChild(entry);
            count++;
        }
    }
}
