using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class AdminMusicWindow : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _console = default!;

    public AdminMusicWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ModeOption.AddItem(Loc.GetString("admin-music-window-mode-global"), 0);
        ModeOption.AddItem(Loc.GetString("admin-music-window-mode-local"), 1);
        ModeOption.SelectId(0);

        HintLabel.Text = Loc.GetString("admin-music-window-hint");

        VolumeSpin.IsValid += value => value is >= -40 and <= 20;
        RangeSpin.IsValid += value => value is >= 1 and <= 40;

        ModeOption.OnItemSelected += args =>
        {
            ModeOption.SelectId(args.Id);
        };

        PlayButton.OnPressed += _ => PlayMusic();
    }

    private void PlayMusic()
    {
        var mode = ModeOption.SelectedId == 1 ? "local" : "global";
        var path = CommandParsing.Escape(PathLine.Text.Trim());
        if (string.IsNullOrWhiteSpace(path))
            return;

        var volume = (int) VolumeSpin.Value;
        var range = (int) RangeSpin.Value;
        _console.ExecuteCommand($"playadminmusic {mode} \"{path}\" {volume} {range}");
    }
}
