# SPDX-FileCopyrightText: 2026 OpenAI
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: Fugitive
  name: roles-antag-fugitive-name
  antagonist: true
  setPreference: true
  objective: roles-antag-fugitive-objective

- type: antag
  id: FugitiveHunter
  name: roles-antag-fugitive-hunter-name
  antagonist: false
  setPreference: true
  objective: roles-antag-fugitive-hunter-objective

- type: startingGear
  id: FugitiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorOrange
    shoes: ClothingShoesColorOrange
    gloves: ClothingHandsGlovesArcGloves
    back: ToolboxMechanicalFilled
    belt: ClothingBeltUtility
    id: PrisonerIDCard
    pocket1: Shiv
  storage:
    belt:
    - CrowbarYellow
    - Wrench
    - Screwdriver
    - Wirecutter
    - Welder
    - Multitool

- type: entity
  parent: PinpointerUniversal
  id: PinpointerFugitiveShip
  name: ship return pinpointer
  description: A pinpointer configured to continuously track the hunter insertion ship.
  components:
  - type: Pinpointer
    canRetarget: false
    updateTargetName: false
  - type: FugitiveShipPinpointer

- type: entity
  parent: PinpointerUniversal
  id: PinpointerFugitiveBounty
  name: fugitive bounty tracker
  description: A pinpointer configured to continuously track fugitive bounties.
  components:
  - type: Pinpointer
    canRetarget: false
    updateTargetName: false
  - type: FugitiveBountyPinpointer

- type: startingGear
  id: FugitiveHunterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterArmorBasic
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackMerc
    belt: ClothingBeltSecurityFilled
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetSecurity
    id: BountyHunterPDA
    pocket1: Zipties
    pocket2: WeaponPistolMk58
  storage:
    back:
    - MagazinePistol
    - MagazinePistol
    - Flash
    - Handcuffs
    - Handcuffs
    - Stunbaton
    - PinpointerFugitiveShip
    - PinpointerFugitiveBounty
